---

- name: install epel-release
  yum:
    name: epel-release
    state: present

- name: install nginx
  yum:
    name: nginx
    state: present

- name: write nginx configuration
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'

- name: create /var/www folder
  file:
    path: /var/www
    state: directory
    owner: nginx
    group: nginx

- name: setup index.html and set color based on variable set in inventory file
  template:
    src: index.html
    dest: /var/www/index.html
    owner: nginx
    group: nginx
    mode: '0644'
    
- name: start nginx service
  service:
    name: nginx
    state: started
    enabled: yes

